snow sql -q "USE ROLE ACCOUNTADMIN;"

snow sql -q "CREATE OR REPLACE WAREHOUSE NATIVE_APP_QUICKSTART_WH WAREHOUSE_SIZE=SMALL INITIALLY_SUSPENDED=TRUE;

-- this database is used to store our data
CREATE OR REPLACE DATABASE NATIVE_APP_QUICKSTART_DB;
USE DATABASE NATIVE_APP_QUICKSTART_DB;

CREATE OR REPLACE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;
USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

-- create provider shipping data table
CREATE OR REPLACE TABLE MFG_SHIPPING (
  order_id NUMBER(38,0), 
  ship_order_id NUMBER(38,0),
  status VARCHAR(60),
  lat FLOAT,
  lon FLOAT,
  duration NUMBER(38,0)
);"

# create consumer orders data table
snow sql -q "USE WAREHOUSE NATIVE_APP_QUICKSTART_WH;
-- this database is used to store our data
USE DATABASE NATIVE_APP_QUICKSTART_DB;

USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

CREATE OR REPLACE TABLE MFG_ORDERS (
  order_id NUMBER(38,0), 
  material_name VARCHAR(60),
  supplier_name VARCHAR(60),
  quantity NUMBER(38,0),
  cost FLOAT,
  process_supply_day NUMBER(38,0)
);

-- create consumer recovery data table
CREATE OR REPLACE TABLE MFG_SITE_RECOVERY (
  event_id NUMBER(38,0), 
  recovery_weeks NUMBER(38,0),
  lat FLOAT,
  lon FLOAT
);
"
snow sql -q "
    CREATE OR REPLACE STAGE NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE
    FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '\"');
"
snow sql -q "
    GRANT READ, WRITE ON STAGE NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE TO ROLE ACCOUNTADMIN;
"

# Upload shipping_data.csv to internal stage
snow sql -q "
    PUT file://app/data/shipping_data.csv @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE AUTO_COMPRESS=TRUE;
"

# Upload order_data.csv to internal stage
snow sql -q "
    PUT file://app/data/order_data.csv @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE AUTO_COMPRESS=TRUE;
"

# Upload site_recovery_data.csv to internal stage
snow sql -q "
    PUT file://app/data/site_recovery_data.csv @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE AUTO_COMPRESS=TRUE;
"

snow sql -q "
    USE WAREHOUSE NATIVE_APP_QUICKSTART_WH;
    USE DATABASE NATIVE_APP_QUICKSTART_DB;
    USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

    -- Load data into MFG_SHIPPING
    COPY INTO MFG_SHIPPING 
    FROM @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE/shipping_data.csv.gz
    FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '\"');

    -- Load data into MFG_ORDERS
    COPY INTO MFG_ORDERS 
    FROM @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE/order_data.csv.gz
    FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '\"');

    -- Load data into MFG_SITE_RECOVERY
    COPY INTO MFG_SITE_RECOVERY 
    FROM @NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE/site_recovery_data.csv.gz
    FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '\"');
"
snow sql -q "
    GRANT USAGE ON DATABASE NATIVE_APP_QUICKSTART_DB TO ROLE ACCOUNTADMIN;
    GRANT USAGE ON SCHEMA NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA TO ROLE ACCOUNTADMIN;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA TO ROLE ACCOUNTADMIN;
    GRANT READ, WRITE ON STAGE NATIVE_APP_QUICKSTART_DB.NATIVE_APP_QUICKSTART_SCHEMA.MY_INTERNAL_STAGE TO ROLE ACCOUNTADMIN;
"
